version: '3.8'

services:
  # postgres: 
  #   image: postgres # hub.docker.com
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES-USER=postgres
  #     - POSTGRES-DB=postgres
  #     - POSTGRES-PASSWORD=password
      
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
    
    